/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2018-09-09 12:48:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import student.com.pjo.Login;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Header.jsp", Long.valueOf(1536299218496L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("student.com.pjo.Login");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Bootstrap/css/bootstrap.min.css\" />\r\n");
      out.write("<script  src=\"Bootstrap/js/jquery.js\"></script>\r\n");
      out.write("<script  src=\"Bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>welcome</title>\r\n");
      out.write("<div class=\"jumbotron\" style=\"background-color:blue; height:150px; padding-top:0px;margin-bottom:0px;\">\r\n");
      out.write("<div align=\"center\" style=\"font-size:25px;padding-top:20px;Color:white;\">Sucess is Sure</div>\r\n");
      out.write("\r\n");
      out.write("</head>");
      out.write('\r');
      out.write('\n');

String bag="img/../img/img5.jpg";
Login user=null;
String act="active";
String title="";
Object obj=session.getAttribute("record");
 user=(Login)obj;

      out.write("\r\n");
      out.write("<body style=\"  background:url(img/../img/ba88.bmp); height:1000px\" >\r\n");
if(user!=null){
      out.write("\r\n");
      out.write("\r\n");
      out.write("<span style=\"color:red; font-size:20px\">welcome:</span> <span style=\"color:white;font-size:20px\"> ");
      out.print(user.getName());
      out.write("</span>\r\n");
      out.write("<br> \r\n");
      out.write("<span style=\"color:red; font-size:20px;\">Role:</span><span style=\"color:white; font-size:20px;\"> ");
      out.print(user.getRole());
      out.write("</span>\r\n");
      out.write("<br><a href=\"logout\"><span  style=\" color:#66FF00;font-size:30px\">Logout</span></a>\r\n");
      out.write(" ");
if(user.getRole().equals("user")){ 
act="disabled";
title="Access only Admin user";

      out.write('\r');
      out.write('\n');
}
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\"> \r\n");
      out.write("<a href=\"Index.jsp\"><button class=\"btn btn-warning btn-lg glyphicon glyphicon-home\">Home</button></a>\r\n");
      out.write("<a href=\"getdept\" title=\"");
      out.print(title);
      out.write("\"><button class=\"btn btn-info btn-lg active\" ");
      out.print(act);
      out.write(">Add Student</button></a>\r\n");
      out.write("<a href=\"addDept.jsp\" title=\"");
      out.print(title);
      out.write("\"><button class=\"btn btn-success btn-lg active\" ");
      out.print(act);
      out.write(">Add Department</button></a>\r\n");
      out.write("<a href=\"view\"><button class=\"btn btn-warning btn-lg active\">View Record</button></a>\r\n");
      out.write("<a href=\"deptView\" title=\"");
      out.print(title);
      out.write("\" ><button class=\"btn btn-success btn-lg active\" ");
      out.print(act);
      out.write(">View Department</button></a>\r\n");
      out.write("</div>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<form class=\"search-form\" action=\"search\" method=\"post\">\r\n");
      out.write("<input type=\"text\" name=\"search\" placeholder=\"Search\" style=\"padding-top:5px; margin-top:8px;\">\r\n");
      out.write("<button class=\"btn btn-success btn-xs\">Search</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
}else{
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"navbar navbar-inverse\" style=\"margin-bottom:0px;\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("<div class=\"navbar-header\">\r\n");
      out.write("<a class=\"navbar-brand\">MySite</a>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"search\" method=\"post\">\r\n");
      out.write("<ul class=\"nav navbar-nav\">\r\n");
      out.write("<li><a href=\"Index.jsp\"><span class=\"glyphicon glyphicon-home\"></span> Home </span></a></li>\r\n");
      out.write("<li class=\"dropdown\">\r\n");
      out.write("<a href=\"#\" class=\"dropdown-toggle\"  data-toggle=\"dropdown\">About <span class=\"caret\"></span></a>\r\n");
      out.write("<ul class=\"dropdown-menu\" style=\"background-color:#910000;\">\r\n");
      out.write("<li><a href=\"#\" style=\"color:#0000FF\">About Campus</a></li>\r\n");
      out.write("<li><a href=\"#\" style=\"color:#0000FF\">About Placement</a></li>\r\n");
      out.write("<li><a href=\"#\" style=\"color:#0000FF\">About new information..</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"#\">Gmail</a></li>\r\n");
      out.write("<li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("<li><a href=\"#\"><span class=\"glyphicon glyphicon-phone-alt\"></span> Contact us</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("<li>\r\n");
      out.write("<form class=\"search-form\">\r\n");
      out.write("<input type=\"text\" name=\"search\" placeholder=\"Search\" style=\"padding-top:5px; margin-top:8px;\">\r\n");
      out.write("<button class=\"btn btn-success btn-xs\">Search</button>\r\n");
      out.write("</form>\r\n");
      out.write("</li>\r\n");
      out.write("<li><a href=\"Login.jsp\"><span class=\"glyphicon glyphicon-user\"></span>Login</a></li>\r\n");
      out.write("<li><a href=\"signup\"><span class=\"glyphicon glyphicon-user\"></span>Signup</a></li>\r\n");
      out.write("<li><a href=\"#\">More <span class=\"glyphicon glyphicon-triangle-right\"></span></a></li>\r\n");
      out.write("<li><img src=\"img/../img/india.png\" height=\"30px\" width=\"60%\" style=\"margin-top:10px\"></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
} 
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
